map_type: costmap
transform_tolerance: 3.0
obstacle_range: 3.0
max_obstacle_height: 2.0
raytrace_range: 3.0

footprint: [[-0.450,-0.430], [-0.630,-0.160], [-0.630,0.160], [-0.450,0.430], [0.300,0.430], [0.490,0.160], [0.490,-0.160], [0.300,-0.430]]

inscribed_radius: 0.35
circumscribed_radius: 0.42
inflation_radius: 0.5
cost_scaling_factor: 15.0
lethal_cost_threshold: 100


observation_sources: base_scan

base_scan: {sensor_frame: base_laser_link, data_type: LaserScan, expected_update_rate: 2.0,
  observation_persistance: 0.0, marking: true, clearing: true}
