#Independent settings for the planner's costmap
global_costmap: 
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0 # 0.5
  raytrace_range: 10.0
  obstacle_range: 10.0
  static_map: true
  rolling_window: false
  width: 50.0
  height: 50.0
  #origin_x:-30.0
  #origin_y:-30.0
  track_unknown_space: true
  unknown_cost_value: 255
  plugins: 
    - {name: static_layer,       type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,        type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}

