#Independent settings for the local planner's costmap
local_costmap: 
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: false # true # 
  rolling_window: true
  width: 5.0 # 15.0
  height: 5.0 # 15.0
  resolution: 0.025
  origin_x: 0.0
  origin_y: 0.0
  plugins: 
    - {name: obstacle_layer,        type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,       type: "costmap_2d::InflationLayer"}    
    - {name: static_layer,          type: "costmap_2d::StaticLayer"}
