base_local_planner: base_local_planner/TrajectoryPlannerROS
TrajectoryPlannerROS:
  transform_tolerance: 3.0
  world_model: costmap
  sim_time: 1.7
  sim_granularity: 0.025
  dwa: false
  vx_samples: 3
  vtheta_samples: 20
  max_vel_x: 0.10
  min_vel_x: 0.05
  max_rotational_vel: 1.0
  min_in_place_vel_th: 0.3
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true
  goal_distance_bias: 0.6
  path_distance_bias: 0.8
  occdist_scale: 0.01
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.05
  escape_reset_dist: 0.15
  escape_reset_theta: 0.30
  acc_lim_theta: 1.0
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  heading_scoring: false
  heading_scoring_timestep: 0.8
  holonomic_robot: false
  simple_attractor: false
  
