base_local_planner: dwa_ais_planner/DWAAISPlannerROS
DWAAISPlannerROS:
  transform_tolerance: 2.0
  world_model: costmap
  sim_time: 2.0     # 2.0
  sim_granularity: 0.025
  vx_samples: 10
  vtheta_samples: 10 # 10
  max_vel_x: 0.6    # 0.6
  min_vel_x: -0.3    # 0.2
  max_trans_vel: 0.6 
  min_trans_vel: -0.3
  max_rot_vel: 0.8
  min_rot_vel: 0.4
  xy_goal_tolerance: 0.25 
  yaw_goal_tolerance: 0.05
  latch_xy_goal_tolerance: false
  goal_distance_bias: 24.0 # 24.0
  path_distance_bias: 32.0
  occdist_scale: 0.01
  forward_point_dist: 0.325
  oscillation_reset_dist: 0.02
  acc_lim_theta: 7.8
  acc_lim_x: 10.0
  acc_lim_y: 0.0
  simple_attractor: false
  max_vel_y: 0.0
  min_vel_y: 0.0

  array_vel_x:
    - 0.6
    - 0.5
    - 0.4
    - 0.3
    - 0.2
    - 0.1
    - 0.05
    - 0.025
    - -0.025
    - -0.05
    - -0.1
    - -0.2

  array_vel_theta:
    - 0.6
    - 0.4
    - 0.3
    - 0.2
    - 0.1
    - 0.05
    - 0.025
    - -0.025
    - -0.05
    - -0.1
    - -0.2
    - -0.3
    - -0.4
    - -0.6

  
  vy_samples: 0
  penalise_negative_x: true
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  controller_frequency: 20
  prune_plan: true
  use_dwa: true
  holonomic_robot: false
  # meter_scoring: true
  heading_scoring: true

  
