base_local_planner: base_local_planner/TrajectoryPlannerROS
TrajectoryPlannerROS:
  transform_tolerance: 2.0
  world_model: costmap
  sim_time: 2.0
  sim_granularity: 0.025
  vx_samples: 3
  vtheta_samples: 20
  max_vel_x: 0.55
  min_vel_x: 0.1
  max_trans_vel: 0.55
  min_trans_vel: 0.1
  max_rot_vel: 3.2
  min_rot_vel: 0.1
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.045
  latch_xy_goal_tolerance: false
  goal_distance_bias: 0.6
  path_distance_bias: 0.6
  occdist_scale: 0.01
  forward_point_dist: 0.325
  oscillation_reset_dist: 0.05
  acc_lim_th: 0.78
  acc_lim_x: 3.0
  acc_lim_y: 0.0
  simple_attractor: false
  max_vel_y: 0.0
  min_vel_y: 0.0
  
  vy_samples: 1
  penalise_negative_x: true
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  controller_frequency: 5
  prune_plan: true
  use_dwa: true
  holonomic_robot: false
  # meter_scoring: true


  
